Drop -Werror.
	Working around:
	# /usr/include/sys/cdefs.h:1:2: error: usage of non-standard #include <sys/cdefs.h> is deprecated [-Werror,-W#warnings]
	# #warning usage of non-standard #include <sys/cdefs.h> is deprecated
	#  ^
	# 1 error generated.